language: node_js
node_js:
  - lts/*

before_script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_KEY.git

jobs:
  include:
    - stage: build
      script:
        - npm install
        - npm run build
    - stage: test
      script: npm test
    - stage: deploy
      if: branch = master
      script: git push -f heroku HEAD:master
